features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://ECA-logo-white.png'
favicon:
  use_default: 0
  path: 'public://favicon-eca.ico'
  mimetype: image/vnd.microsoft.icon
mobile_menu_all_widths: 0
site_branding_bg_color: default
base_primary_color: '#57919e'
